---
permalink: performance-checker/concept_um_interfaces_used_to_manage_storage_system_performance.html 
sidebar: sidebar 
keywords: unified manager, interfaces, used, manage, storage, system, performance, web ui, maintenance, console 
summary: 'Active IQ Unified Manager proporciona dos interfaces de usuario para supervisar y solucionar problemas de rendimiento del almacenamiento de datos: La interfaz de usuario web y la consola de mantenimiento.' 
---
= Las interfaces de Unified Manager que se utilizan para gestionar el rendimiento del sistema de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager proporciona dos interfaces de usuario para supervisar y solucionar problemas de rendimiento del almacenamiento de datos: La interfaz de usuario web y la consola de mantenimiento.



== Interfaz de usuario web de Unified Manager

La interfaz de usuario web de Unified Manager permite a un administrador supervisar y solucionar los problemas del sistema de almacenamiento relacionados con el rendimiento.

Estas secciones describen algunos flujos de trabajo comunes que puede seguir un administrador para solucionar problemas de rendimiento del almacenamiento que se muestran en la interfaz de usuario web de Unified Manager.



== Consola de mantenimiento

La consola de mantenimiento permite a un administrador supervisar, diagnosticar y solucionar problemas del sistema operativo, problemas de actualización de la versión, problemas de acceso del usuario y problemas de red relacionados con el servidor de Unified Manager mismo. Si la interfaz de usuario web de Unified Manager no está disponible, la consola de mantenimiento es el único formato de acceso a Unified Manager.

Estas secciones proporcionan instrucciones para acceder a la consola de mantenimiento y utilizarla para resolver los problemas relacionados con el funcionamiento del servidor de Unified Manager.
